/// FOR SERVICES PAGE
export const SERVICES_FETCH_DATA_SUCCESS = "SERVICES_FETCH_DATA_SUCCESS";
export const ADD_SERVICE = "ADD_SERVICE";
export const EDIT_SERVICE = "EDIT_SERVICE";
export const DELETE_SERVICE = "DELETE_SERVICE";
/// FOR APPOINTMENTS PAGE
export const APPOINTMENTS_FETCH_DATA_SUCCESS = "APPOINTMENTS_FETCH_DATA_SUCCESS";
export const ADD_APPOINTMENT = "ADD_APPOINTMENT";
export const EDIT_APPOINTMENT = "EDIT_APPOINTMENT";
export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT";
/// FOR WITHDRAWALS PAGE
export const WITHDRAWALS_FETCH_DATA_SUCCESS = "WITHDRAWALS_FETCH_DATA_SUCCESS";
export const ADD_WITHDRAWAL = "ADD_WITHDRAWAL";
export const EDIT_WITHDRAWAL = "EDIT_WITHDRAWAL";
export const DELETE_WITHDRAWAL = "DELETE_WITHDRAWAL";
/// FOR PRODUCTS PAGE
export const PRODUCTS_FETCH_DATA_SUCCESS = "PRODUCTS_FETCH_DATA_SUCCESS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
// FOR USER_PROFILES PAGE
export const USER_PROFILE_FETCH_DATA_SUCCESS = "USER_PROFILE_FETCH_DATA_SUCCESS";
export const ADD_USER_PROFILE = "ADD_USER_PROFILE";
export const EDIT_USER_PROFILE = "EDIT_USER_PROFILE";
export const DELETE_USER_PROFILE = "DELETE_USER_PROFILE";
// FOR DEPOSITS PAGE
export const DEPOSITS_FETCH_DATA_SUCCESS = "DEPOSITS_FETCH_DATA_SUCCESS";
export const ADD_DEPOSIT = "ADD_DEPOSIT";
export const EDIT_DEPOSIT = "EDIT_DEPOSIT";
export const DELETE_DEPOSIT = "DELETE_DEPOSIT";